# -*- coding: utf-8 -*-
"""ходилка+парсинг.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DHNP6HsQMKwKPqAm6S9YkfqDxqXsPChH
"""

import requests
import googlesearch
from bs4 import BeautifulSoup

def get_page(url):
    return requests.get(url).text

def extract_main_text(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')
    main_text = soup.get_text()
    return main_text

def find_answer(question):
    # Используем Google для поиска URL по вопросу
    search_results = googlesearch.search(question, num=1, stop=1)

    if search_results:
        website_url = next(search_results)
        print("Найден URL сайта:", website_url)

        # Получаем содержимое веб-страницы
        html_content = get_page(website_url)

        # Извлекаем весь текст с веб-страницы
        main_text = extract_main_text(html_content)

        return main_text
    else:
        return "Сайт не найден."

# Пример использования:
question = input("Введите вопрос: ")

answer = find_answer(question)
print("Ответ:", answer)

import requests
import googlesearch
from bs4 import BeautifulSoup

def get_page(url):
    return requests.get(url).text

def extract_main_text(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')
    main_text = soup.get_text("\n", strip=True)  # Удаление лишних пробелов и переносов строк
    return main_text

def find_answer(question):
    # Используем Google для поиска URL по вопросу
    search_results = googlesearch.search(question, num=1, stop=1)

    if search_results:
        website_url = next(search_results)
        print("Найден URL сайта:", website_url)

        # Получаем содержимое веб-страницы
        html_content = get_page(website_url)

        # Извлекаем весь текст с веб-страницы
        main_text = extract_main_text(html_content)

        return main_text
    else:
        return "Сайт не найден."

# Пример использования:
question = input("Введите вопрос: ")

answer = find_answer(question)
print("Ответ:")
print(answer)